# Generated by Django 6.1.1 on 2026-09-26 13:08

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'modalidade',
                'verbose_name_plural': 'modalidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Espaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('QUADRA', 'Quadra'), ('CAMPO', 'Campo'), ('PISCINA', 'Piscina'), ('GINASIO', 'Ginásio'), ('SALAO', 'Salão')], default='QUADRA', max_length=10)),
                ('descricao', models.TextField(blank=True)),
                ('capacidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('preco_hora', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('coberto', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('horario_abertura', models.TimeField(default=datetime.time(8, 0))),
                ('horario_fechamento', models.TimeField(default=datetime.time(22, 0))),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('modalidades', models.ManyToManyField(blank=True, related_name='espacos', to='reservas.modalidade')),
            ],
            options={
                'verbose_name': 'espaço',
                'verbose_name_plural': 'espaços',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=120)),
                ('cliente_email', models.EmailField(max_length=254)),
                ('cliente_telefone', models.CharField(blank=True, max_length=20)),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=10)),
                ('observacoes', models.TextField(blank=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.espaco')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['-data', 'hora_inicio'],
            },
        ),
        migrations.AddConstraint(
            model_name='espaco',
            constraint=models.CheckConstraint(condition=models.Q(('horario_fechamento__gt', models.F('horario_abertura'))), name='espaco_fechamento_apos_abertura'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('hora_fim__gt', models.F('hora_inicio'))), name='reserva_fim_apos_inicio'),
        ),
    ]
