# Generated by Django 6.1.1 on 2026-09-26 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espaco',
            name='modalidades',
        ),
        migrations.DeleteModel(
            name='Modalidade',
        ),
    ]
